"""create life areas and goals

Revision ID: 4a10246e89fa
Revises:
Create Date: 2026-07-29 20:22:18.782597
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a10246e89fa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применить изменение схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "life_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("current_score", sa.Integer(), nullable=False),
        sa.Column("desired_score", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_score BETWEEN 1 AND 10", name="ck_life_areas_current_score"
        ),
        sa.CheckConstraint(
            "desired_score BETWEEN 1 AND 10", name="ck_life_areas_desired_score"
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name="ck_life_areas_priority"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("life_area_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "horizon",
            sa.Enum(
                "week",
                "month",
                "quarter",
                "year",
                "three_years",
                name="goal_horizon",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "paused",
                "completed",
                "cancelled",
                name="goal_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("achievement_criteria", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name="ck_goals_priority"),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100", name="ck_goals_progress_percent"
        ),
        sa.CheckConstraint(
            "target_date IS NULL OR start_date IS NULL OR target_date >= start_date",
            name="ck_goals_date_order",
        ),
        sa.ForeignKeyConstraint(
            ["life_area_id"], ["life_areas.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goals_life_area_id"), "goals", ["life_area_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Отменить изменение схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goals_life_area_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_table("life_areas")
    # ### end Alembic commands ###
